@host = https://bopay.iyes.dev
@contentType = application/json
@superuser="admin002"


### Register an user

POST {{ host }}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "admin002",
    "password": "123321",
}


### Login

POST {{ host }}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "admin002",
    "password": "123123"
}


### UserList
GET {{ host }}/api/users HTTP/1.1

### UserDetail
GET {{ host }}/api/users/10001 HTTP/1.1

### UserUpdate
POST {{ host }}/api/users/10001 HTTP/1.1

{
    "email":"new@aaa.com",
    "name":"鲑鱼",
    "phone":"1111111"
}

### UserDelete
DELETE {{ host }}/api/users/10001 HTTP/1.1