@host = https://bopay.iyes.dev
@contentType = application/json
@superuser="admin002"


### Register an user

POST {{ host }}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "admin002",
    "password": "123321"
}


### Login

POST {{ host }}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "admin002",
    "password": "123321"
}


### UserList
GET {{ host }}/api/users HTTP/1.1

### UserDetail
GET {{ host }}/api/users/10001 HTTP/1.1

### UserUpdate
POST {{ host }}/api/users/10001 HTTP/1.1

{
    "email":"new@aaa.com",
    "name":"鲑鱼",
    "phone":"1111111"
}

### UserDelete
DELETE {{ host }}/api/users/10001 HTTP/1.1


### OrderList
GET {{ host }}/api/orders?page=2&per_page=3 HTTP/1.1


### DeveloperCreate

POST http://{{ host }}/api/developers HTTP/1.1
Content-Type: {{contentType}}

{
    "user_id": 10003,
    "username": "dev001",
    "is_active": true,
    "name": "开发者测试000",
    "org": "YLCorp",
    "email": "yl@iyes.dev",
    "note": "测试用途"
}

### RegisterDeveloper

POST http://{{ host }}/auth/register/developer HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "dev002",
    "password": "123321",
    "org": "测试公司",
    "info": "伟大的公司",
    "phone": "181818181",
    "email": "aqwefq@qq.com",
    "site": "www.baidu.com",
    "telegram": "@f88xxq"
}


### AppCreate

POST http://{{ host }}/api/apps/new HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "vns2",
    "name_cn": "威尼斯人8888",
    "info": "",
    "callback_url": "http://nx.iyes.dev/payment/bopay"
}


### Crypto Search API
GET http://{{ host }}/api/cryptowallets?page=1 HTTP/1.1

### CryptoAccts Search API
GET http://{{ host }}/api/cryptoaccts?page=1 HTTP/1.1

### LoginLogs Search API
GET http://{{ host }}/api/loginlogs?page=1 HTTP/1.1

### 加密钱包 List API
GET http://{{ host }}/api/cryptowallets?page=1 HTTP/1.1

### 加密钱包账号 List API
GET http://{{ host }}/api/cryptoaccts?wallet_id=101&page=1 HTTP/1.1

### 新增加密账号 Create API
POST http://{{ host }}/api/cryptoaccts HTTP/1.1
Content-Type: application/json

{
    "wallet_id": 101,
    "name": "钱包1的地址",
    "seq": 1,
    "w": 0,
    "note": "备注",
    "address": "0x10100110",
    "currency": 1
}

### 审核订单
POST http://{{ host }}/api/orders/approve HTTP/1.1

{
    "id": 103,
    "amount_paid": 10003,
    "comments": "审核已到账"
}


### 拒绝订单
POST http://{{ host }}/api/orders/deny HTTP/1.1

{
    "id": 100,
    "comments": "欺诈订单"
}

### 取消订单
POST http://{{ host }}/api/orders/100/cancel HTTP/1.1


### 订单通知
POST http://{{ host }}/api/orders/100/notify HTTP/1.1


### 加密货币账变流水记录 CryptoAcctLogList

GET {{ host }}/api/cryptoacctlogs HTTP/1.1


### 绑定订单和加密货币账变日志, 操作按钮放在加密货币账变记录

POST http://{{ host }}/api/orders/bind HTTP/1.1
Content-Type: {{contentType}}

{
    "order_id": 7,
    "crypto_acct_log_id": 1342,
    "amount_paid": 1160000,
    "note": "测试一下绑定, 正确支付金额应该是 1260000"
}


### 预下单，开放API 接入

POST http://{{ host }}/payments/orders HTTP/1.1
Content-Type: {{contentType}}
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwMDJ9.wWYyGs3kDhS_qRZrWESDXg8g-5CmiQ-wDQvC57wOEfs
X-Appid: 20002

{
    "userid": "843812904",
    "currency": 2,
    "pay_type": 4,
    "amount": 1250000,
    "device_type": 0,
    "client_ip": "2607:f0d0:1002:0051:0000:0000:0000:0004"
}


### Roles list
GET http://{{ host }}/api/roles HTTP/1.1

### Role's Users 角色下的用户列表
GET http://{{ host }}/api/roles/1/users HTTP/1.1


### Roles Update Perms 更新角色权限列表
POST http://{{ host }}/api/roles/1/perms HTTP/1.1
Content-Type: {{contentType}}

{
    "role.List": true,
    "role.Delete": false
}


### Role Add Users 角色添加用户
POST http://{{ host }}/api/roles/1/users/add HTTP/1.1
Content-Type: {{contentType}}

[ 10027,10037,10047, 1, 3232 , 10001]


### Role Del Users 角色删除用户, 值为 user.id
POST http://{{ host }}/api/roles/1/users/del HTTP/1.1
Content-Type: {{contentType}}

[ 10027,10037,10047, 1, 3232 ]
